name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  macos:
    runs-on: macOS-latest
    steps:
      - name: checkout this repo
        uses: actions/checkout@v2
      - name: checkout kerl repo
        uses: actions/checkout@v2
        with:
          repository: kerl/kerl
          path: kerl
      - name: Build
        run: |
          set -ex
          kerl/kerl build 22.0.7
        env:
          DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer
