name: CI
on:
  push:
    branches: [master]
env:
  OTP_RELEASE: 22.0.7
jobs:
  build_and_release:
    strategy:
      matrix:
        platform: [ubuntu-18.04, macos-10.15]
        wx: [headless, graphical]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: checkout this repo
        uses: actions/checkout@v2
      - name: checkout kerl repo
        uses: actions/checkout@v2
        with:
          repository: kerl/kerl
          path: kerl
      - name: checkout wxwidgets repo
        uses: actions/checkout@v2
        with:
          repository: wxWidgets/wxWidgets
          ref: WX_3_0_BRANCH
          path: wxwidgets
      - name: Build wxWidgets
        if: ${{ matrix.wx == 'graphical' }}
        shell: bash
        run: |
          set -ex
          ./build_wxwidgets.bash wxwidgets ~/wx-install
      - name: Build OTP
        run: |
          set -ex
          PATH="${PATH}:${HOME}/wx-install/bin"
          export KERL_CONFIGURE_DISABLE_APPLICATIONS="megaco eldap snmp mnesia et diameter"
          kerl/kerl build ${OTP_RELEASE}
          kerl/kerl install ${OTP_RELEASE} my_release
          tar -czf my_release.tar.gz my_release/*
          echo '================================================================================================================================'
          cat ~/.kerl/builds/22.0.7/otp_build_22.0.7.log
          echo '================================================================================================================================'
        env:
          DEVELOPER_DIR: /Applications/Xcode_11.3.1.app/Contents/Developer
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ matrix.platform }}-${{ matrix.wx }}-${{ github.sha }}
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./my_release.tar.gz
          asset_name: otp_${{ env.OTP_RELEASE }}.tar.gz
          asset_content_type: application/gzip
