name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  macos:
    runs-on: macOS-latest
    steps:
      - name: checkout this repo
        uses: actions/checkout@v2
      - name: Build
        run: |
          set -ex
          OTP_VERSION=22.0.7
          OTP_DOWNLOAD_SHA256=04c090b55ec4a01778e7e1a5b7fdf54012548ca72737965b7aa8c4d7878c92bc
          OTP_DOWNLOAD_URL="https://github.com/erlang/otp/archive/OTP-${OTP_VERSION}.tar.gz"
          OTP_DOWNLOAD_SHA256="${OTP_DOWNLOAD_SHA256}" 
          curl -fSL -o otp-src.tar.gz "${OTP_DOWNLOAD_URL}" 
          echo "$OTP_DOWNLOAD_SHA256  otp-src.tar.gz" | sha256sum -c - 
          export ERL_TOP="/usr/src/otp_src_${OTP_VERSION%%@*}"
          mkdir -vp ${ERL_TOP}
          tar -xzvf otp-src.tar.gz -C ${ERL_TOP} --strip-components=1
        env:
          DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer
